### ISSUE TITLE
License

### ISSUE THREAD

**Issue by matze298** [jayroxis/dam-pytorch#1]
Hi,
we're interested in using your code for one of our projects.
Could you please tell us, what license your code is under and/or provide the respective License file in the repo?
You might not be aware of it, but without an explicit license, no-one can legally use your code: http://opensource.stackexchange.com/q/1720/775

Thanks in advance!

**Comment by jayroxis** [comment]
Hi Matthias,

Thanks and I think it’s under MIT license. You may use it or distribute it
as long as it’s cited when needed.

Best regards,
Jie Bu

**Comment by matze298** [comment]
Thanks for your answer. Could you maybe add the appropriate license file? 
Thanks!

**Comment by jayroxis** [comment]
> Thanks for your answer. Could you maybe add the appropriate license file? Thanks!

Hi matze,

The license file has been added to the repo.

Thanks.
